repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    - id: autopep8
      args:
        - --in-place
        - --ignore=E26,E265,E266,E402,E501

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.0.0
    hooks:
      - id: doctoc
        exclude: ^vendor/
